name: Snake animation

on:
  schedule:
    - cron: '0 0 * * *' # todo dia à meia-noite UTC
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake
        uses: liqd/github-contribution-snake@v1.2.0
        with:
          fileName: 'github-contribution-grid-snake.svg'
          color: '36abf7'
          background: '0D1117'
          width: 20
          height: 20
          radius: 4

      - name: Commit and push snake
        run: |
          git config user.name "Fabrini Bot"
          git config user.email "fabrini-bot@example.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution snake [skip ci]" || echo "No changes to commit"
          git push
